variables:
  IMAGE_TAG: latest

image: docker:latest

stages:
  - build
  - deploy

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  stage: build
  only:
    - master
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" -f Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
